### ISSUE TITLE
no distribution provided for node_modules include

### ISSUE THREAD

**Issue by drujensen** [rotorz/markdown-it-external-links#5]
There is no es6 -> es5 distribution provided so its failing to compile when trying to deploy.

**Comment by kruncher** [comment]
This is package does not include an ES5 distribution by design to keep things simple.

If you need an ES5 distribution then you will need to perform the transformation yourself using the likes of [babel.js](https://babeljs.io/), [TypeScript](https://www.typescriptlang.org/), or [Traceur Compiler](https://github.com/google/traceur-compiler).
